#!/bin/sh
# SPDX-License-Identifier: CC0-1.0
# 2021-2022 by The Foundation for Public Code <info@publiccode.net>

# This script is used to generate a PDF from the html generated by Jekyll.

# The 'serve.sh' script should be called prior to this script in order to
# create and serve html content on localhost:4000

# This script is used during the release process (see ../docs/releasing.md)

weasyprint http://localhost:4000/print.html standard.pdf --presentational-hints
weasyprint http://localhost:4000/print-cover.html standard-cover.pdf --presentational-hints
weasyprint http://localhost:4000/print-review-template.html review-template.pdf --presentational-hints
